import { getAccessContext } from "./accessContext.js";
import { buildIntakeClassification } from "./systemDesign/classification.js";

export const DEMO_PORTFOLIO = {
  name: "Global Balanced Endowment",
  allocations: [
    { assetClass: "Public Equity – Developed Markets", weight: 32, region: "US / Europe" },
    { assetClass: "Investment Grade Fixed Income", weight: 18, region: "US" },
    { assetClass: "Private Equity", weight: 17, region: "North America" },
    { assetClass: "Real Assets / Infrastructure", weight: 11, region: "Global" },
    { assetClass: "High Yield / Credit", weight: 9, region: "US / Europe" },
    { assetClass: "Private Credit", weight: 6, region: "North America" },
    { assetClass: "Cash & Equivalents", weight: 4, region: "USD" },
    { assetClass: "Hedge Funds / Alternatives", weight: 3, region: "Global" },
  ],
  duration: 5.8,
  leverage: 1.2,
  liquidityProfile: "Mixed (40–80% liquid within 30 days)",
  constraints: "Preserve annual spending stability, avoid forced selling, maintain ESG exclusions.",
};

export const DEMO_ANALYSIS_META = {
  provider: "OpenAI",
  mode: "demo",
  modelLabel: "Proposal Demo Dataset",
  promptVersion: "demo-v1",
  schemaVersion: "2026-03-10",
  systemDesignVersion: "2026-03-10",
  accessContext: getAccessContext("local-demo"),
  intakeClassification: null,
  dataSources: ["Proposal Demo Dataset"],
  dataAsOf: "2026-03-10",
  contextVersion: "demo-v1",
  marketSummary: "Demo market context represents a diversified inflation, growth, and liquidity stress backdrop for committee review.",
  providerStatus: [],
  indicatorValues: {},
};

export const DEMO_RESULTS = {
  exposures: {
    analysisSummary: "The portfolio is pro-cyclical with moderate inflation hedging, but liquidity and refinancing pressure can amplify losses when private-market valuations reset.",
    exposureMap: {
      inflationSensitivity: { score: 6, drivers: ["Real assets provide partial hedge", "Equity multiples compress if inflation stays sticky"], interpretation: "Inflation protection exists, but it is offset by rate-sensitive growth and private valuations." },
      growthSensitivity: { score: 7, drivers: ["Private equity earnings depend on growth durability", "Developed market equity sleeve is cyclically exposed"], interpretation: "Growth disappointments would flow quickly into public equity and more slowly into private marks." },
      durationRisk: { score: 5, drivers: ["Intermediate IG sleeve", "Infrastructure valuations remain discount-rate sensitive"], interpretation: "Duration is meaningful but not dominant relative to cyclical and liquidity risk." },
      creditSpreadRisk: { score: 8, drivers: ["HY and private credit refinancing needs", "Private marks may lag spread widening"], interpretation: "Credit stress is a primary transmission channel because spreads and financing availability hit multiple sleeves at once." },
      currencyExposure: { score: 4, drivers: ["Global DM equity holdings", "Infrastructure cash flows span regions"], interpretation: "Currency risk is present but secondary because most liabilities and liquid reserves are USD-based." },
      liquidityDependence: { score: 8, drivers: ["Private market allocations exceed 20%", "Spending policy depends on liquid public sleeves"], interpretation: "The portfolio depends on public-market liquidity to fund obligations while private assets reprice slowly." },
    },
    dominantExposures: ["Credit spread widening across public and private books", "Liquidity dependence driven by private capital and spending needs"],
    hiddenConcentrations: ["Infrastructure and private equity both rely on benign refinancing markets", "Public equity and HY sleeves share the same pro-cyclical growth exposure"],
  },
  regimeAssessment: {
    regimeSetSummary: "The scenario set spans inflation, growth, and funding stress so the committee can compare macro shocks with different liquidity consequences.",
    regimes: [
      {
        id: 1,
        name: "Sticky Inflation, Restrictive Rates",
        scenarioType: "Inflation policy shock",
        probability: "Medium",
        timeHorizon: "6-18M",
        trigger: "Services inflation stalls above target and central banks hold policy tight for longer than markets expect.",
        transmissionMechanisms: ["Real yields stay elevated and compress valuation multiples", "Financing costs rise for leveraged issuers and private assets", "Liquidity shifts toward short-duration safe assets"],
        equityImpact: "Bearish",
        fixedIncomeImpact: "Bearish",
        privateMarketsImpact: "Bearish",
        creditImpact: "Bearish",
        realAssetsImpact: "Neutral",
        keyRisk: "Private valuations and credit spreads reprice faster than spending needs adjust.",
        rationaleSummary: "This regime hurts the portfolio through discount-rate pressure and tighter financing conditions rather than an outright collapse in growth.",
        historicalAnalogy: {
          episode: "2022 Inflation Reset",
          matchScore: 76,
          parallels: ["Rates and spreads reprice before fundamentals fully weaken", "Private asset marks lag public-market repricing"],
          differences: ["Today’s starting credit quality is somewhat stronger than in early 2022"],
        },
      },
      {
        id: 2,
        name: "Growth Slowdown with Credit Strain",
        scenarioType: "Demand contraction",
        probability: "Medium",
        timeHorizon: "3-12M",
        trigger: "Labor demand weakens and earnings revisions turn sharply negative while defaults begin to rise.",
        transmissionMechanisms: ["Cyclical equities de-rate as earnings fall", "Credit losses rise in leveraged and sponsor-backed issuers", "Liquidity premiums widen across private markets"],
        equityImpact: "Bearish",
        fixedIncomeImpact: "Neutral",
        privateMarketsImpact: "Bearish",
        creditImpact: "Bearish",
        realAssetsImpact: "Neutral",
        keyRisk: "Spread widening and delayed private-market markdowns obscure the true loss path.",
        rationaleSummary: "This is the regime where the portfolio’s hidden overlap between private equity, HY, and private credit becomes most visible.",
        historicalAnalogy: {
          episode: "2001-2002 Earnings Recession",
          matchScore: 63,
          parallels: ["Growth-sensitive assets weaken before balance sheets fully reset", "Credit differentiation matters more than duration"],
          differences: ["Private capital markets are far larger and slower-moving today"],
        },
      },
      {
        id: 3,
        name: "Liquidity Vacuum in Private Markets",
        scenarioType: "Funding and liquidity stress",
        probability: "Low",
        timeHorizon: "0-6M",
        trigger: "A policy or market accident causes secondary market liquidity to gap lower and refinancing windows to close temporarily.",
        transmissionMechanisms: ["Bid-ask spreads widen across credit and listed risk assets", "Capital calls and spending needs compete for the same liquid assets", "Governance pressure rises as stale marks diverge from executable prices"],
        equityImpact: "Bearish",
        fixedIncomeImpact: "Bullish",
        privateMarketsImpact: "Bearish",
        creditImpact: "Bearish",
        realAssetsImpact: "Bearish",
        keyRisk: "Forced selling risk rises even if long-term asset values are not permanently impaired.",
        rationaleSummary: "The portfolio can absorb mark-to-market pain, but a liquidity vacuum forces action on the least desirable timetable.",
        historicalAnalogy: {
          episode: "March 2020 Liquidity Shock",
          matchScore: 81,
          parallels: ["Liquidity disappears faster than committees can rebalance", "Safe assets outperform while private marks lag"],
          differences: ["Current cash buffers are better than many institutions carried into 2020"],
        },
      },
    ],
  },
  regimes: [],
  vulnerabilityAssessment: {
    analysisSummary: "Portfolio fragility is concentrated where illiquid assets rely on liquid sleeves for governance flexibility and cash management.",
    vulnerabilities: [
      {
        regimeId: 1,
        regimeName: "Sticky Inflation, Restrictive Rates",
        firstOrderEffects: ["Infrastructure and IG valuations weaken as discount rates stay elevated", "HY and private credit spreads widen, reducing financing flexibility"],
        secondOrderEffects: ["Spending-policy pressure may force sales of liquid public assets before private marks reset"],
        liquidityStress: "Medium",
        estimatedDrawdown: "-7% to -11%",
        vulnerabilityScore: 7,
        primaryVulnerability: "Financing-sensitive private assets repricing alongside weaker liquid buffers",
        reasoningSummary: "Losses accumulate through slower-moving valuation resets and tighter financing markets rather than an immediate balance-sheet shock.",
      },
      {
        regimeId: 2,
        regimeName: "Growth Slowdown with Credit Strain",
        firstOrderEffects: ["Public equities and HY absorb negative earnings revisions", "Private equity and private credit underwriting assumptions weaken"],
        secondOrderEffects: ["Distribution slowdown extends denominator effect and reduces optionality"],
        liquidityStress: "High",
        estimatedDrawdown: "-9% to -14%",
        vulnerabilityScore: 8,
        primaryVulnerability: "Cyclical overlap across public equity, HY, and sponsor-backed private assets",
        reasoningSummary: "The same growth shock hits multiple sleeves, creating correlation where the portfolio appears diversified in normal markets.",
      },
      {
        regimeId: 3,
        regimeName: "Liquidity Vacuum in Private Markets",
        firstOrderEffects: ["Secondary liquidity dries up for private holdings", "Credit bid-ask spreads widen and public liquidity becomes expensive"],
        secondOrderEffects: ["Forced-selling risk rises if capital calls or spending needs arrive at the wrong moment"],
        liquidityStress: "Critical",
        estimatedDrawdown: "-6% to -10%",
        vulnerabilityScore: 9,
        primaryVulnerability: "Mismatch between illiquid commitments and short-notice cash needs",
        reasoningSummary: "Even if the ultimate impairment is modest, governance stress is severe because action windows shrink before committees can respond.",
      },
    ],
  },
  vulnerabilities: [],
  governance: {
    rci: { score: 58, label: "Guarded", rationale: "The main vulnerability channels are clear, but path dependency around inflation and liquidity remains meaningful.", uncertaintyBand: "Moderate" },
    lci: { score: 67, label: "Elevated", rationale: "Liquid sleeves appear sufficient in normal conditions but can thin quickly if distributions slow and capital calls cluster.", forcedSellingRisk: "High" },
    escalationLevel: 3,
    escalationLabel: "Committee Review",
    escalationRationale: "The combination of high liquidity fragility and cross-book credit sensitivity warrants committee review before the next allocation decision.",
    escalationTriggers: ["LCI remains above 60 for two consecutive reviews", "Private-market distributions slow materially versus spending needs", "Credit spreads widen while refinancing markets weaken"],
    governanceActions: ["Run a liquidity coverage review against capital calls and spending needs", "Stress-test the liquid sleeve required to defend the governance budget", "Pre-approve escalation messaging for a sudden private-market liquidity shock"],
    counterScenario: "A soft landing with faster disinflation would preserve liquidity and make current caution look overly defensive, especially if private exits re-open.",
    keyWatchItems: ["Distribution pace from private funds", "Refinancing spreads for HY and sponsor-backed borrowers", "Cash buffer coverage for 12-month spending requirements"],
    decisionContext: "The portfolio is not in immediate crisis, but governance flexibility is narrower than the headline diversification profile suggests.",
    humanValidationChecks: ["Validate private capital cash-flow assumptions with current manager reports", "Confirm spending policy can be met without selling risk assets into stress", "Review whether escalation thresholds align with investment committee tolerance"],
    committeeMemoHeadline: "Governance attention should center on liquidity resilience rather than point-estimate return forecasting.",
  },
};

DEMO_RESULTS.regimes = DEMO_RESULTS.regimeAssessment.regimes;
DEMO_RESULTS.vulnerabilities = DEMO_RESULTS.vulnerabilityAssessment.vulnerabilities;

DEMO_ANALYSIS_META.intakeClassification = buildIntakeClassification(DEMO_PORTFOLIO, {
  asOf: DEMO_ANALYSIS_META.dataAsOf,
  sourcesUsed: DEMO_ANALYSIS_META.dataSources,
});
