export const INDICATORS = {
  headline_cpi_yoy: {
    id: "headline_cpi_yoy",
    label: "Headline CPI YoY",
    category: "inflation",
    unit: "pct",
    frequency: "monthly",
    transform: "yoy",
    valueDigits: 1,
    revalidate: 60 * 60 * 24,
    providers: ["bls", "fred"],
    bls: { seriesId: "CUUR0000SA0" },
    fred: { seriesId: "CPIAUCSL" },
  },
  core_cpi_yoy: {
    id: "core_cpi_yoy",
    label: "Core CPI YoY",
    category: "inflation",
    unit: "pct",
    frequency: "monthly",
    transform: "yoy",
    valueDigits: 1,
    revalidate: 60 * 60 * 24,
    providers: ["bls", "fred"],
    bls: { seriesId: "CUUR0000SA0L1E" },
    fred: { seriesId: "CPILFESL" },
  },
  ppi_yoy: {
    id: "ppi_yoy",
    label: "PPI YoY",
    category: "inflation",
    unit: "pct",
    frequency: "monthly",
    transform: "yoy",
    valueDigits: 1,
    revalidate: 60 * 60 * 24,
    providers: ["bls", "fred"],
    bls: { seriesId: "WPUFD4" },
    fred: { seriesId: "PPIACO" },
  },
  breakeven_10y: {
    id: "breakeven_10y",
    label: "10Y Breakeven Inflation",
    category: "inflation",
    unit: "pct",
    frequency: "daily",
    transform: "level",
    valueDigits: 2,
    revalidate: 60 * 60 * 4,
    providers: ["fred"],
    fred: { seriesId: "T10YIE" },
  },
  payroll_growth_yoy: {
    id: "payroll_growth_yoy",
    label: "Nonfarm Payroll Growth YoY",
    category: "growth",
    unit: "pct",
    frequency: "monthly",
    transform: "yoy",
    valueDigits: 1,
    revalidate: 60 * 60 * 24,
    providers: ["bls", "fred"],
    bls: { seriesId: "CES0000000001" },
    fred: { seriesId: "PAYEMS" },
  },
  industrial_production_yoy: {
    id: "industrial_production_yoy",
    label: "Industrial Production YoY",
    category: "growth",
    unit: "pct",
    frequency: "monthly",
    transform: "yoy",
    valueDigits: 1,
    revalidate: 60 * 60 * 24,
    providers: ["fred"],
    fred: { seriesId: "INDPRO" },
  },
  real_gdp_growth_qoq_annualized: {
    id: "real_gdp_growth_qoq_annualized",
    label: "Real GDP Growth (QoQ annualized)",
    category: "growth",
    unit: "pct",
    frequency: "quarterly",
    transform: "level",
    valueDigits: 1,
    revalidate: 60 * 60 * 24,
    providers: ["bea", "fred"],
    bea: { datasetName: "NIPA", tableName: "T10101", lineNumber: 1, frequency: "Q", year: "X" },
    fred: { seriesId: "A191RL1Q225SBEA" },
  },
  unemployment_rate: {
    id: "unemployment_rate",
    label: "Unemployment Rate",
    category: "labor",
    unit: "pct",
    frequency: "monthly",
    transform: "level",
    valueDigits: 1,
    revalidate: 60 * 60 * 24,
    providers: ["bls", "fred"],
    bls: { seriesId: "LNS14000000" },
    fred: { seriesId: "UNRATE" },
  },
  wage_growth_yoy: {
    id: "wage_growth_yoy",
    label: "Average Hourly Earnings YoY",
    category: "labor",
    unit: "pct",
    frequency: "monthly",
    transform: "yoy",
    valueDigits: 1,
    revalidate: 60 * 60 * 24,
    providers: ["bls", "fred"],
    bls: { seriesId: "CES0500000003" },
    fred: { seriesId: "CES0500000003" },
  },
  treasury_2y_yield: {
    id: "treasury_2y_yield",
    label: "2Y Treasury Yield",
    category: "rates",
    unit: "pct",
    frequency: "auction",
    transform: "level",
    valueDigits: 2,
    revalidate: 60 * 60 * 6,
    providers: ["treasury", "fred"],
    treasury: { securityTerm: "2-Year" },
    fred: { seriesId: "DGS2" },
  },
  treasury_10y_yield: {
    id: "treasury_10y_yield",
    label: "10Y Treasury Yield",
    category: "rates",
    unit: "pct",
    frequency: "auction",
    transform: "level",
    valueDigits: 2,
    revalidate: 60 * 60 * 6,
    providers: ["treasury", "fred"],
    treasury: { securityTerm: "10-Year" },
    fred: { seriesId: "DGS10" },
  },
  real_yield_10y: {
    id: "real_yield_10y",
    label: "10Y Real Yield",
    category: "rates",
    unit: "pct",
    frequency: "daily",
    transform: "level",
    valueDigits: 2,
    revalidate: 60 * 60 * 4,
    providers: ["fred"],
    fred: { seriesId: "DFII10" },
  },
  policy_rate_upper: {
    id: "policy_rate_upper",
    label: "Fed Funds Upper Bound",
    category: "rates",
    unit: "pct",
    frequency: "daily",
    transform: "level",
    valueDigits: 2,
    revalidate: 60 * 60 * 4,
    providers: ["fred"],
    fred: { seriesId: "DFEDTARU" },
  },
  credit_spread_proxy: {
    id: "credit_spread_proxy",
    label: "Baa Credit Spread Proxy",
    category: "credit",
    unit: "pct",
    frequency: "monthly",
    transform: "level",
    valueDigits: 2,
    revalidate: 60 * 60 * 12,
    providers: ["fred"],
    fred: { seriesId: "BAA10YM" },
  },
  financial_conditions_index: {
    id: "financial_conditions_index",
    label: "National Financial Conditions Index",
    category: "credit",
    unit: "x",
    frequency: "weekly",
    transform: "level",
    valueDigits: 2,
    revalidate: 60 * 60 * 12,
    providers: ["fred"],
    fred: { seriesId: "NFCI" },
  },
};

export const DERIVED_INDICATORS = {
  yield_curve_10y_2y: {
    id: "yield_curve_10y_2y",
    label: "10Y-2Y Yield Curve",
    category: "rates",
    unit: "pct",
    valueDigits: 2,
    sourceIndicators: ["treasury_10y_yield", "treasury_2y_yield"],
  },
};

export const REQUIRED_CONTEXT_INDICATORS = [
  "headline_cpi_yoy",
  "unemployment_rate",
  "payroll_growth_yoy",
  "treasury_10y_yield",
  "yield_curve_10y_2y",
];

export const MINIMUM_REQUIRED_CONTEXT_INDICATORS = 4;

export function getIndicatorDefinition(indicatorId) {
  return INDICATORS[indicatorId] || DERIVED_INDICATORS[indicatorId] || null;
}

export function listContextIndicators() {
  return [
    "headline_cpi_yoy",
    "core_cpi_yoy",
    "ppi_yoy",
    "breakeven_10y",
    "real_gdp_growth_qoq_annualized",
    "payroll_growth_yoy",
    "industrial_production_yoy",
    "unemployment_rate",
    "wage_growth_yoy",
    "policy_rate_upper",
    "treasury_2y_yield",
    "treasury_10y_yield",
    "yield_curve_10y_2y",
    "real_yield_10y",
    "credit_spread_proxy",
    "financial_conditions_index",
  ];
}
